name: Build Personal Diary APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-8-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev \
          build-essential libssl-dev libffi-dev \
          python3-dev python3-setuptools

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-8-openjdk-amd64/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install kivy==2.1.0
        pip install buildozer==1.4.0
        pip install cython==0.29.33

    - name: Initialize buildozer
      run: |
        buildozer init || true

    - name: Build debug APK
      run: |
        buildozer android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: personal-diary-debug-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-logs-failure
        path: |
          .buildozer/
          *.log
        retention-days: 7
